version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building the React app...
      - npm run build
  post_build:
    commands:
      - echo Build completed. Preparing for deployment...

artifacts:
  files:
    - '**/*'
  base-directory: build  # Specifies the build output directory to deploy

cache:
  paths:
    - 'node_modules/**/*'
